language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9

cache:
  - pip
  - directories:
    - rest_framework_docs/static/node_modules/

before_install:
  - nvm install 5

install:
  - cd rest_framework_docs/static/ && npm install && cd ../../
  - pip install -r requirements.txt
  - pip install -U Django==$DJANGO_VERSION
  - pip install codecov

script:
  - python runtests.py

after_success:
  - codecov

notifications:
  slack:
    secure: ZTzxh+tXuf7uaFMBQtrjupS+qqtM3dsnYgHptErsg3SjH0q1jH+HpKD+1RlqGqN36mREB1wSlOhGMzfyGNeNhl0PHQLEtZhs3dRLdzR1xMZWKm7xtCe4TcFoSPh5SoLOHrQVaSEyHeE53gkbOfI7Q5SqVRJOlJv9iCCD8TM+KVdDubCeByevunFSzGFwdLvtk7QpRwXivOGJdJHXXWgVl6ieviQKun5Z03woiLr5L4p37szVkbD60T5lFYAhCL1PzLQ6hVhDn7L4J06LIaQ+l+Jp6cunB1iJtR1Rz+C7g/r2VGgJ5G3sHB3QyFqw9Q/E3oBB81xQTwjL7WSfDuKctW2CPWHac0T9VhidQDoq7uR0EYPMkZXnc+iZa5wmL8IfjEadse0rxdfiIOE+mev+i5BrzHBq/+tZV/D+HKzsRXUEf3BZaRpq7gQHWbj0dusX+R504BQtKqYaGqBFdWJ0+Dry739R4xTeWk10Xa3wpzSFQ1c0yUQbY+3W/DNSYKcRV+Z9eGhMSO1QfBlGzqTlkWkVDnD9OYIpo5iJOkDouJVtzPOyyFBoNGqkvUHiKBO6ohuh48S3xXrjhihkz8xuOSrU1W7xGhCG2RA/vHZh8Fm20l1oIJ/p/Gn6kTLT33XZsxnF9C0Qmgvr6f96MKNPJjNKp0zYj4tJaZr9Xi4rsD8=
