title: Django Rest Framework Docs

description: Document Web APIs made with Django Rest Framework

baseurl: "" # the subpath of your site, e.g. /blog

url: "http://www.drfdocs.com" # the base hostname & protocol for your site

collections:
  docs:
    output: true
    permalink: /docs/:path/

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc

twitter_username: iamemmanouil
github_username:  ekonstantinidis
github_repo_url: ekonstantinidis/django-rest-framework-docs

# Build settings
markdown: kramdown
exclude: ['node_modules', 'package.json']
