#!/usr/bin/env bash
BRANCH=master
TARGET_REPO=ekonstantinidis/django-rest-framework-docs.git
DOCS_FOLDER=docs

# if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then

    if [ "$TRAVIS" == "true" ]; then
        git config --global user.email "manos@iamemmanouil.com"
        git config --global user.name "ekonstantinidis"
    fi

    echo -e "Starting deployment on Github Pages\n"

    # Using token clone gh-pages branch
    git clone --quiet --branch=$BRANCH https://${GH_TOKEN}@github.com/$TARGET_REPO cloned_repo > /dev/null

    # Go into directory and copy data we're interested in to that directory
    cd cloned_repo
    rsync -rv --exclude=.git  ../$DOCS_FOLDER/* .

    # Add, commit and push files
    git add -f .
    git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to Github Pages"
    git push -fq origin $BRANCH > /dev/null

    echo -e "Deploy completed\n"

# fi
